CREATE TABLE TAB_DEV_INFO (
	APPID not null auto_increment ,
	HOUSEID TEXT NOT NULL,
	APPINFO TEXT NOT NULL,
	REGISTERTIME TEXT NOT NULL,
	MOBILEPHONE TEXT NOT NULL,
	RECORDSTATUS TEXT NOT NULL,
	SPC10 TEXT NOT NULL,
	SPC20 TEXT NOT NULL,
	SPC50 TEXT NOT NULL,
	SPC100 TEXT NOT NULL
};
alter table t add primary key (id);


CREATE TABLE TAB_DEV_INFO (
	IDCARD TEXT PRIVATE KEY (IDCARD)£¬
	USERNAME TEXT NOT NULL,
	IMAGEPATH TEXT NOT NULL,
	MOBILEPHONE TEXT NOT NULL,
	SPC10 TEXT NOT NULL,
	SPC20 TEXT NOT NULL,
	SPC50 TEXT NOT NULL,
	SPC100 TEXT NOT NULL
};

CREATE TABLE TAB_AUTH_INFO (
  	AUTHID TEXT PRIVATE KEY (AUTHID)£¬
  	IDCARD TEXT NOT NULL,
  	HOUSEID TEXT NOT NULL,
  	SPC10 TEXT NOT NULL,
  	SPC20 TEXT NOT NULL,
  	SPC50 TEXT NOT NULL,
  	SPC100 TEXT NOT NULL
};

CREATE TABLE TAB_HOUSE_INFO (
	HOUSEID TEXT PRIVATE KEY (HOUSEID)£¬
	HOUSEINFO TEXT NOT NULL,
	SCHEMEID TEXT NOT NULL,
	HOUSEADDR TEXT NOT NULL,
	SPC10 TEXT NOT NULL,
	SPC20 TEXT NOT NULL,
	SPC50 TEXT NOT NULL,
	SPC100 TEXT NOT NULL
};

CREATE TABLE TAB_SCHEMA_INFO (
	SCHEMAID integer not null primary key auto_increment£¬
	HOUSEID TEXT NOT NULL,
	MODE TEXT NOT NULL,
	SCHEMASTARTTIME TEXT NOT NULL,
	SCHEMAENDTIME TEXT NOT NULL,
	SPC10 TEXT NOT NULL,
	SPC20 TEXT NOT NULL,
	SPC50 TEXT NOT NULL,
	SPC100 TEXT NOT NULL
};
